inherit_gem:
  jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - vendor/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-target-blank.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*
